fix ci

diff --git a/bin/syncup b/bin/syncup
--- a/bin/syncup
+++ b/bin/syncup
@@ -7,40 +7,27 @@ green=$(tput setaf 2)
 yellow=$(tput setaf 3)
 
 myexit() {
-  reason=$1
-  printf "${red}Failed: ${reason}!!!\n"
+  printf "${red}Failed: %b!!!\n" "$1"
   exit 1
 }
 
-# default "`pwd`"
-repo_path=$1
-[ -z ${repo_path} ] && repo_path=$(pwd)
-[ -d $repo_path ] || myexit "First parameter is not directory"
-# default "current branch"
-branch=$2
-if [[ -z $branch ]]; then
-  branch=$(git rev-parse --abbrev-ref HEAD)
-fi
 # checks if it's a git repo
 check_repo() {
-  if [ ! -d $(pwd)/.git ]; then
+  if [ ! -d "$(pwd)"/.git ]; then
     myexit "$(pwd) is not a git repo"
   fi
 }
 
 # checks if there is a remote repo called upstream
-check_upstream() {
-  git remote -v | grep -w upstream >/dev/null
-  # if there are no remote repository called upstream
-  if [ $? -ne 0 ]; then
-    myexit "Upstream not configured in this repo($(pwd))"
-  fi
+upstream_exists() {
+  # return 0 if exists
+  git remote -v | grep -w upstream >/dev/null 2>&1
 }
 
 # check if a branch was passed as parameter and if not it makes the master as the default branch
 check_branch() {
   if [[ $branch ]]; then
-    printf "${green}Branch to sync to is set to ${yellow}${branch}${green}\n"
+    printf "${green}Branch to sync to is set to ${yellow}%s${green}\n" "$branch"
   else
     myexit "Branch to sync not configured"
   fi
@@ -50,20 +37,31 @@ check_branch() {
 # merges upstream with a given branch
 # push the changes
 sync() {
-  printf "${green}Fetching its updates...\n"
-  git fetch upstream
-  if [ $? -eq 0 ]; then
-    printf "${green}Merging updates with ${yellow}${branch}${green}\n"
-    git merge upstream/$branch
+  printf "${green}%s\n" "Fetching its updates..."
+  ret=$(git fetch upstream)
+  if $ret; then
+    printf "${green}Merging updates with ${yellow}%s${green}\n" "$branch"
+    git merge upstream/"$branch"
     git push
   else
     myexit "Failed fetch upstream"
   fi
 }
 
-cur_path=$(pwd)
-cd $repo_path
-check_repo
-check_upstream
-check_branch
-sync
+main() {
+  # default "`pwd`"
+  repo_path=$1
+  [ -z "${repo_path}" ] && repo_path=$(pwd)
+  [ -d "$repo_path" ] || myexit "First parameter is not directory"
+  # default "current branch"
+  branch=$2
+  [ -z "$branch" ] && branch=$(git rev-parse --abbrev-ref HEAD)
+  cd "$repo_path" || exit
+  check_repo
+  # if there are no remote repository called upstream
+  upstream_exists || myexit "Upstream not configured in this repo($(pwd))"
+  check_branch
+  sync
+}
+
+main "$@"
